spring.application.name=workshopmongo

# Força a URI completa apontando para o localhost e para a porta padrão do Compass
spring.mongodb.uri=mongodb://127.0.0.1:27017/workshop_mongo

# Configuração extra para garantir que o Spring não use instâncias embutidas ou isoladas
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=workshop_mongo